name: MEGA-CORE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pytest
    - flake8
    - networkx
    - skyfield
    - gunicorn
    - python-Levenshtein
    - spacy
    - flask
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.0/en_core_web_sm-3.7.0.tar.gz
