name: MEGA-CORE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  - flake8
  - networkx
  - skyfield
  - flask
  - pip:
    - gunicorn
    - python-Levenshtein
    - spacy
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.0/en_core_web_sm-3.7.0.tar.gz
