name: MEGA-CORE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  - flake8
  - networkx
  - skyfield
  - python-Levenshtein
  - Flask
  - gunicorn
  - spacy
  - pip:
    - en_core_web_sm
