name: Deploy Web Portal

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest

      - name: Run Web Server
        run: |
          gunicorn --bind 0.0.0.0:5000 app:app &
          echo "Web server is running."

      - name: Run Main Script
        run: |
          python main.py
